{
 "title": "Feelgood Web",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Frontend Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg Request Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "reqps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (job) (rate(haproxy_backend_http_responses_total{job=\"frontend-service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Avg Error Rate past 5m",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (code, app) (app:haproxy_backend_http_errors_per_response:ratio_rate5m{job=\"frontend-service\"})"
    }
   ]
  },
  {
   "title": "Avg Latency (s)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (job) (rate(haproxy_backend_http_total_time_average_seconds{job=\"frontend-service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Error Rate SLO over 5m",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "app:error_slo:percent{job=\"frontend-service\"}"
    }
   ]
  },
  {
   "title": "Breaching Error Rate SLO over 5m",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  app:haproxy_backend_http_errors_per_response:ratio_rate5m{job=\"frontend-service\"}\n  >\n  bool app:error_slo:percent{job=\"frontend-service\"}\n)"
    }
   ]
  },
  { "title": "API Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Avg Request Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "format": "reqps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (job) (rate(haproxy_backend_http_responses_total{job=\"feelgood-api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Avg Error Rate past 5m",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "app:haproxy_backend_http_errors_per_response:ratio_rate5m{job=\"feelgood-api\"}"
    }
   ]
  },
  {
   "title": "Avg Latency (s)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (job) (rate(haproxy_backend_http_total_time_average_seconds{job=\"feelgood-api\"}[1m]))"
    }
   ]
  },
  { "title": "Frontend RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Request Rate / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(haproxy_backend_http_requests_total{job=\"frontend-service\"}[1m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Error Rate / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (job, code) (rate(haproxy_backend_http_responses_total{code=\"5xx\", job=\"frontend-service\"}[1m]))",
     "legendFormat": "{{ code }}: {{ job }}"
    }
   ]
  },
  {
   "title": "Duration (s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(haproxy_backend_http_total_time_average_seconds{job=\"frontend-service\"}[1m]))",
     "legendFormat": "latency: {{ job }}"
    }
   ]
  },
  { "title": "API RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Request Rate / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(haproxy_backend_http_requests_total{job=\"feelgood-api\"}[1m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Error Rate / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (job, code) (rate(haproxy_backend_http_responses_total{code=\"5xx\", job=\"feelgood-api\"}[1m]))",
     "legendFormat": "{{ code }}: {{ job }}"
    }
   ]
  },
  {
   "title": "Duration (s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(haproxy_backend_http_total_time_average_seconds{job=\"feelgood-api\"}[1m]))",
     "legendFormat": "latency: {{ job }}"
    }
   ]
  },
  { "title": "Frontend Ambassador", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Frontend Circuit Breaker State",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (breaker_state) (rate(http_requests_total{job=\"frontend-service\"}[1m]))",
     "legendFormat": "{{ breaker_state }}"
    }
   ]
  },
  {
   "title": "Frontend Circuit Breaker Latency (s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, breaker_state) (rate(http_request_duration_seconds_bucket{job=\"frontend-service\"}[5m])))",
     "legendFormat": "99th %ile: {{ breaker_state }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, breaker_state) (rate(http_request_duration_seconds_bucket{job=\"frontend-service\"}[5m])))",
     "legendFormat": "95th %ile: {{ breaker_state }}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le, breaker_state) (rate(http_request_duration_seconds_bucket{job=\"frontend-service\"}[5m])))",
     "legendFormat": "50th %ile: {{ breaker_state }}"
    }
   ]
  }
 ]
}