{
 "title": "Feelgood Web",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Frontend Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Latency (s)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
     "format": "s",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum without (endpoint, instance, namespace, proxy, service, pod) (rate(haproxy_backend_http_total_time_average_seconds{job=\"frontend-service\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Avg Request Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "reqps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum without(endpoint, instance, pod, service, proxy, namespace, code) (rate(haproxy_backend_http_responses_total{job=\"frontend-service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Avg Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "reqps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum without(endpoint, instance, pod, service, proxy, namespace) (rate(haproxy_backend_http_responses_total{code=\"5xx\", job=\"frontend-service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Avg Latency (s)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum without (endpoint, instance, namespace, proxy, service, pod) (rate(haproxy_backend_http_total_time_average_seconds{job=\"frontend-service\"}[1m]))"
    }
   ]
  },
  { "title": "API Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Avg Request Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "format": "reqps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum without(endpoint, instance, pod, service, proxy, namespace, code) (rate(haproxy_backend_http_responses_total{job=\"feelgood-api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Avg Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 5 },
   "format": "reqps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum without(endpoint, instance, pod, service, proxy, namespace) (rate(haproxy_backend_http_responses_total{code=\"5xx\", job=\"feelgood-api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Avg Latency (s)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum without (endpoint, instance, namespace, proxy, service, pod) (rate(haproxy_backend_http_total_time_average_seconds{job=\"feelgood-api\"}[1m]))"
    }
   ]
  },
  { "title": "Frontend RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Request Rate / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum without(endpoint, instance, namespace, pod, proxy, service) (rate(haproxy_backend_http_requests_total{job=\"frontend-service\"}[1m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Error Rate / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum without(endpoint, instance, pod, service, proxy, namespace) (rate(haproxy_backend_http_responses_total{code=\"5xx\", job=\"frontend-service\"}[1m]))",
     "legendFormat": "{{ code }}: {{ job }}"
    }
   ]
  },
  {
   "title": "Duration (s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without (endpoint, instance, namespace, proxy, service, pod) (rate(haproxy_backend_http_total_time_average_seconds{job=\"frontend-service\"}[1m]))",
     "legendFormat": "latency: {{ job }}"
    }
   ]
  },
  { "title": "API RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Request Rate / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum without(endpoint, instance, namespace, pod, proxy, service) (rate(haproxy_backend_http_requests_total{job=\"feelgood-api\"}[1m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Error Rate / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum without(endpoint, instance, pod, service, proxy, namespace) (rate(haproxy_backend_http_responses_total{code=\"5xx\", job=\"feelgood-api\"}[1m]))",
     "legendFormat": "{{ code }}: {{ job }}"
    }
   ]
  },
  {
   "title": "Duration (s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without (endpoint, instance, namespace, proxy, service, pod) (rate(haproxy_backend_http_total_time_average_seconds{job=\"feelgood-api\"}[1m]))",
     "legendFormat": "latency: {{ job }}"
    }
   ]
  }
 ]
}