---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config-api
  namespace: default
  labels:
    version: v1
data:
  haproxy.cfg: |
    global
        maxconn 100

    defaults
        mode http
        timeout connect 5s
        timeout client 5s
        timeout server 5s

    frontend proxy
        bind *:80
        mode http
        default_backend api

    frontend stats
        bind *:9091
        option http-use-htx
        http-request use-service prometheus-exporter if { path /metrics }
        stats enable
        stats uri /stats
        stats refresh 10s

    backend api
        server feelgood_api localhost:8080
