---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
  labels:
    version: initial
data:
  PORT: "4200"
  GO_ENV: "development"
  API_ADDR: "http://feelgood-api"
