apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: feelgood-api
  labels:
    app: feelgood-api
    release: gophercon
    version: v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: feelgood-api
        release: gophercon
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: feelgood
          image: 'awesome-corp/feelgood-api:0.0.3'
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /var/log/feelgood
              name: app-log
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
        - name: logger
          image: alpine:3.10
          command: ["tail"]
          args: ["-f", "/var/log/feelgood/server.log"]
          volumeMounts:
            - mountPath: /var/log/feelgood
              name: app-log
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
        - name: proxy
          image: 'haproxy:2.0.4'
          ports:
            - containerPort: 80
            - containerPort: 9091
          volumeMounts:
            - mountPath: /usr/local/etc/haproxy/
              name: haproxy-cfg
          resources:
            limits:
              cpu: 400m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: haproxy-cfg
          configMap:
            name: haproxy-config
        - name: app-log
          emptyDir: {}
