apiVersion: v1
kind: Service
metadata:
  name: feelgood-api
  labels:
    app: feelgood-api
    release: gophercon
    version: v2
spec:
  selector:
    app: feelgood-api
    release: gophercon
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics
      protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP
