package main

type message struct {
	Content string `json:"message"`
}

var messages = []message{
	message{"You are more fun than anyone or anything I know, including bubble wrap."},
	message{"You are the most perfect you there is."},
	message{"You are awesome."},
	message{"You're wonderful."},
	message{"You're great at figuring stuff out."},
	message{"You're better than a triple-scoop ice cream cone. With sprinkles."},
	message{"Any team would be lucky to have you on it."},
	message{"You're even better than a unicorn, because you're real."},
	message{"You're even better than a unicorn, because you're real."},
	message{"You're even better than a unicorn, because you're real."},
	message{"Gopher's are awesome."},
	message{"Gopher's are awesome."},
	message{"Ya'll are looking amazing today."},
	message{"You are a top geezer."},
	message{"Great haircut."},
	message{"You're a smart cookie."},
	message{"You look great today."},
	message{"You're like a ray of sunshine on a really dreary day."},
	message{"You have the best smile."},
	message{"Your outlook on life is amazing."},
	message{"You just light up the room."},
	message{"You make a bigger impact than you realise."},
	message{"You just glow."},
	message{"You have the best laugh."},
	message{"I love the way you bring out the best in people."},
	message{"You are always so helpful."},
	message{"You have the best sense of style."},
	message{"You have the best sense of style."},
	message{"You make me want to be a better person."},
	message{"Everything seems brighter when you are around."},
	message{"You are one of the bravest people I know."},
	message{"You really seem to know who you are. I admire that."},
	message{"You're not an imposter."},
	message{"I am really glad we met."},
	message{"It doesn't look like you're screwing this up Davy."},
	message{"It doesn't look like you're screwing this up Davy."},
	message{"It doesn't look like you're screwing this up Davy."},
	message{"It doesn't look like you're screwing this up Davy."},
	message{"It doesn't look like you're screwing this up Davy."},
	message{"I'm sorry, Dave. I'm afraid I can't do that."},
	message{"I'm sorry, Dave. I'm afraid I can't do that."},
	message{"I enjoy spending time with you."},
	message{"You’re a gift to everyone you meet."},
	message{"I tell everyone how amazing you are."},
}
